name: Run Curbed Web Scrape Extract and Load to Raw

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

env:
  PG_USER:       ${{ secrets.PG_USER }}
  PG_PASSWORD:   ${{ secrets.PG_PASSWORD }}
  PG_HOST:       ${{ secrets.PG_HOST }}
  PG_DB:         ${{ secrets.PG_DB }}

jobs:
  web-scrape:
    name: Extract and Load Raw Curbed Web Data
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install papermill

      - name: Run Curbed Web Scrape Notebook
        run: |
          papermill notebooks/Curbed_Web_Scrape_Extract_Load_Raw.ipynb notebooks/Curbed_Web_Scrape_Extract_Load_Raw_output.ipynb


